//------------------------------------------------------------------------------
// <auto-generated>
//     Koden er generert av et verktøy.
//     Kjøretidsversjon:2.0.50727.8000
//
//     Endringer i denne filen kan føre til feil virkemåte, og vil gå tapt hvis
//     koden genereres på nytt.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace PolarConverter.BLL.Entiteter
{ // 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="activity-info", Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot("activity-info", Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class activityinfo {
    
        private string stepsField;
    
        private string infitnesszoneField;
    
        private string inhealthzoneField;
    
        /// <remarks/>
        [XmlElement(DataType="nonNegativeInteger")]
        public string steps {
            get {
                return this.stepsField;
            }
            set {
                this.stepsField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("in-fitness-zone")]
        public string infitnesszone {
            get {
                return this.infitnesszoneField;
            }
            set {
                this.infitnesszoneField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("in-health-zone")]
        public string inhealthzone {
            get {
                return this.inhealthzoneField;
            }
            set {
                this.inhealthzoneField = value;
            }
        }
    }

    /// <remarks/>
    [XmlInclude(typeof(timestampAdapter))]
    [XmlInclude(typeof(durationAdapter))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    public abstract partial class xmlAdapter {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    public partial class timestampAdapter : xmlAdapter {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    public partial class durationAdapter : xmlAdapter {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    public abstract partial class range {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="short-range", Namespace="http://www.polarpersonaltrainer.com")]
    public partial class shortrange {
    
        private short minimumField;
    
        private bool minimumFieldSpecified;
    
        private short averageField;
    
        private bool averageFieldSpecified;
    
        private short maximumField;
    
        private bool maximumFieldSpecified;
    
        /// <remarks/>
        public short minimum {
            get {
                return this.minimumField;
            }
            set {
                this.minimumField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool minimumSpecified {
            get {
                return this.minimumFieldSpecified;
            }
            set {
                this.minimumFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public short average {
            get {
                return this.averageField;
            }
            set {
                this.averageField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool averageSpecified {
            get {
                return this.averageFieldSpecified;
            }
            set {
                this.averageFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public short maximum {
            get {
                return this.maximumField;
            }
            set {
                this.maximumField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool maximumSpecified {
            get {
                return this.maximumFieldSpecified;
            }
            set {
                this.maximumFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="float-range", Namespace="http://www.polarpersonaltrainer.com")]
    public partial class floatrange {
    
        private float minimumField;
    
        private bool minimumFieldSpecified;
    
        private float averageField;
    
        private bool averageFieldSpecified;
    
        private float maximumField;
    
        private bool maximumFieldSpecified;
    
        /// <remarks/>
        public float minimum {
            get {
                return this.minimumField;
            }
            set {
                this.minimumField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool minimumSpecified {
            get {
                return this.minimumFieldSpecified;
            }
            set {
                this.minimumFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public float average {
            get {
                return this.averageField;
            }
            set {
                this.averageField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool averageSpecified {
            get {
                return this.averageFieldSpecified;
            }
            set {
                this.averageFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public float maximum {
            get {
                return this.maximumField;
            }
            set {
                this.maximumField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool maximumSpecified {
            get {
                return this.maximumFieldSpecified;
            }
            set {
                this.maximumFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="byte-range", Namespace="http://www.polarpersonaltrainer.com")]
    public partial class byterange {
    
        private sbyte minimumField;
    
        private bool minimumFieldSpecified;
    
        private sbyte averageField;
    
        private bool averageFieldSpecified;
    
        private sbyte maximumField;
    
        private bool maximumFieldSpecified;
    
        /// <remarks/>
        public sbyte minimum {
            get {
                return this.minimumField;
            }
            set {
                this.minimumField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool minimumSpecified {
            get {
                return this.minimumFieldSpecified;
            }
            set {
                this.minimumFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public sbyte average {
            get {
                return this.averageField;
            }
            set {
                this.averageField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool averageSpecified {
            get {
                return this.averageFieldSpecified;
            }
            set {
                this.averageFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public sbyte maximum {
            get {
                return this.maximumField;
            }
            set {
                this.maximumField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool maximumSpecified {
            get {
                return this.maximumFieldSpecified;
            }
            set {
                this.maximumFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot(Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class move {
    
        private strengthactivity activityField;
    
        private float weightField;
    
        private bool weightFieldSpecified;
    
        private sbyte setsField;
    
        private bool setsFieldSpecified;
    
        private byterange repetitionsField;
    
        private string starttimeField;
    
        private string endtimeField;
    
        private string indexField;
    
        /// <remarks/>
        public strengthactivity activity {
            get {
                return this.activityField;
            }
            set {
                this.activityField = value;
            }
        }
    
        /// <remarks/>
        public float weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool weightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public sbyte sets {
            get {
                return this.setsField;
            }
            set {
                this.setsField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool setsSpecified {
            get {
                return this.setsFieldSpecified;
            }
            set {
                this.setsFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public byterange repetitions {
            get {
                return this.repetitionsField;
            }
            set {
                this.repetitionsField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("start-time")]
        public string starttime {
            get {
                return this.starttimeField;
            }
            set {
                this.starttimeField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("end-time")]
        public string endtime {
            get {
                return this.endtimeField;
            }
            set {
                this.endtimeField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="nonNegativeInteger")]
        public string index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="strength-activity", Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot("strength-activity", Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class strengthactivity {
    
        private string nameField;
    
        private activityRegion regionField;
    
        private bool regionFieldSpecified;
    
        private float oneroundmaximumField;
    
        private bool oneroundmaximumFieldSpecified;
    
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    
        /// <remarks/>
        public activityRegion region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool regionSpecified {
            get {
                return this.regionFieldSpecified;
            }
            set {
                this.regionFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("one-round-maximum")]
        public float oneroundmaximum {
            get {
                return this.oneroundmaximumField;
            }
            set {
                this.oneroundmaximumField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool oneroundmaximumSpecified {
            get {
                return this.oneroundmaximumFieldSpecified;
            }
            set {
                this.oneroundmaximumFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    public enum activityRegion {
    
        /// <remarks/>
        LEGS,
    
        /// <remarks/>
        CHEST,
    
        /// <remarks/>
        DELTS,
    
        /// <remarks/>
        BACK,
    
        /// <remarks/>
        ARMS,
    
        /// <remarks/>
        ABS,
    
        /// <remarks/>
        NONE,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot(Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class zone {
    
        private short upperField;
    
        private bool upperFieldSpecified;
    
        private short lowerField;
    
        private bool lowerFieldSpecified;
    
        private string aboveField;
    
        private string inzoneField;
    
        private string belowField;
    
        private float calorieexpenditureField;
    
        private bool calorieexpenditureFieldSpecified;
    
        private string indexField;
    
        /// <remarks/>
        public short upper {
            get {
                return this.upperField;
            }
            set {
                this.upperField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool upperSpecified {
            get {
                return this.upperFieldSpecified;
            }
            set {
                this.upperFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public short lower {
            get {
                return this.lowerField;
            }
            set {
                this.lowerField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool lowerSpecified {
            get {
                return this.lowerFieldSpecified;
            }
            set {
                this.lowerFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public string above {
            get {
                return this.aboveField;
            }
            set {
                this.aboveField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("in-zone")]
        public string inzone {
            get {
                return this.inzoneField;
            }
            set {
                this.inzoneField = value;
            }
        }
    
        /// <remarks/>
        public string below {
            get {
                return this.belowField;
            }
            set {
                this.belowField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("calorie-expenditure")]
        public float calorieexpenditure {
            get {
                return this.calorieexpenditureField;
            }
            set {
                this.calorieexpenditureField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool calorieexpenditureSpecified {
            get {
                return this.calorieexpenditureFieldSpecified;
            }
            set {
                this.calorieexpenditureFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="nonNegativeInteger")]
        public string index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot(Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class phase {
    
        private float upperField;
    
        private bool upperFieldSpecified;
    
        private float lowerField;
    
        private bool lowerFieldSpecified;
    
        private string durationField;
    
        private string indexField;
    
        /// <remarks/>
        public float upper {
            get {
                return this.upperField;
            }
            set {
                this.upperField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool upperSpecified {
            get {
                return this.upperFieldSpecified;
            }
            set {
                this.upperFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public float lower {
            get {
                return this.lowerField;
            }
            set {
                this.lowerField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool lowerSpecified {
            get {
                return this.lowerFieldSpecified;
            }
            set {
                this.lowerFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="nonNegativeInteger")]
        public string index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot(Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class lap {
    
        private string durationField;
    
        private heartraterange heartrateField;
    
        private floatrange speedField;
    
        private shortrange cadenceField;
    
        private power powerField;
    
        private floatrange temperatureField;
    
        private float altitudeField;
    
        private bool altitudeFieldSpecified;
    
        private float ascentField;
    
        private bool ascentFieldSpecified;
    
        private float descentField;
    
        private bool descentFieldSpecified;
    
        private float distanceField;
    
        private bool distanceFieldSpecified;
    
        private short directionField;
    
        private bool directionFieldSpecified;
    
        private endingvalues endingvaluesField;
    
        private string indexField;
    
        /// <remarks/>
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("heart-rate")]
        public heartraterange heartrate {
            get {
                return this.heartrateField;
            }
            set {
                this.heartrateField = value;
            }
        }
    
        /// <remarks/>
        public floatrange speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
            }
        }
    
        /// <remarks/>
        public shortrange cadence {
            get {
                return this.cadenceField;
            }
            set {
                this.cadenceField = value;
            }
        }
    
        /// <remarks/>
        public power power {
            get {
                return this.powerField;
            }
            set {
                this.powerField = value;
            }
        }
    
        /// <remarks/>
        public floatrange temperature {
            get {
                return this.temperatureField;
            }
            set {
                this.temperatureField = value;
            }
        }
    
        /// <remarks/>
        public float altitude {
            get {
                return this.altitudeField;
            }
            set {
                this.altitudeField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool altitudeSpecified {
            get {
                return this.altitudeFieldSpecified;
            }
            set {
                this.altitudeFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public float ascent {
            get {
                return this.ascentField;
            }
            set {
                this.ascentField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool ascentSpecified {
            get {
                return this.ascentFieldSpecified;
            }
            set {
                this.ascentFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public float descent {
            get {
                return this.descentField;
            }
            set {
                this.descentField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool descentSpecified {
            get {
                return this.descentFieldSpecified;
            }
            set {
                this.descentFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public float distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool distanceSpecified {
            get {
                return this.distanceFieldSpecified;
            }
            set {
                this.distanceFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public short direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool directionSpecified {
            get {
                return this.directionFieldSpecified;
            }
            set {
                this.directionFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("ending-values")]
        public endingvalues endingvalues {
            get {
                return this.endingvaluesField;
            }
            set {
                this.endingvaluesField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="nonNegativeInteger")]
        public string index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="heart-rate-range", Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot("heart-rate", Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class heartraterange {
    
        private short restingField;
    
        private bool restingFieldSpecified;
    
        private short minimumField;
    
        private bool minimumFieldSpecified;
    
        private short averageField;
    
        private bool averageFieldSpecified;
    
        private short maximumField;
    
        private bool maximumFieldSpecified;
    
        private short endingField;
    
        private bool endingFieldSpecified;
    
        /// <remarks/>
        public short resting {
            get {
                return this.restingField;
            }
            set {
                this.restingField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool restingSpecified {
            get {
                return this.restingFieldSpecified;
            }
            set {
                this.restingFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public short minimum {
            get {
                return this.minimumField;
            }
            set {
                this.minimumField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool minimumSpecified {
            get {
                return this.minimumFieldSpecified;
            }
            set {
                this.minimumFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public short average {
            get {
                return this.averageField;
            }
            set {
                this.averageField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool averageSpecified {
            get {
                return this.averageFieldSpecified;
            }
            set {
                this.averageFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public short maximum {
            get {
                return this.maximumField;
            }
            set {
                this.maximumField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool maximumSpecified {
            get {
                return this.maximumFieldSpecified;
            }
            set {
                this.maximumFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public short ending {
            get {
                return this.endingField;
            }
            set {
                this.endingField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool endingSpecified {
            get {
                return this.endingFieldSpecified;
            }
            set {
                this.endingFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot(Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class power {
    
        private shortrange power1Field;
    
        private floatrange pedalindexField;
    
        private float leftrightbalanceField;
    
        private bool leftrightbalanceFieldSpecified;
    
        /// <remarks/>
        [XmlElement("power")]
        public shortrange power1 {
            get {
                return this.power1Field;
            }
            set {
                this.power1Field = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("pedal-index")]
        public floatrange pedalindex {
            get {
                return this.pedalindexField;
            }
            set {
                this.pedalindexField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("left-right-balance")]
        public float leftrightbalance {
            get {
                return this.leftrightbalanceField;
            }
            set {
                this.leftrightbalanceField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool leftrightbalanceSpecified {
            get {
                return this.leftrightbalanceFieldSpecified;
            }
            set {
                this.leftrightbalanceFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="ending-values", Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot("ending-values", Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class endingvalues {
    
        private short heartrateField;
    
        private bool heartrateFieldSpecified;
    
        private float speedField;
    
        private bool speedFieldSpecified;
    
        private short cadenceField;
    
        private bool cadenceFieldSpecified;
    
        /// <remarks/>
        [XmlElement("heart-rate")]
        public short heartrate {
            get {
                return this.heartrateField;
            }
            set {
                this.heartrateField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool heartrateSpecified {
            get {
                return this.heartrateFieldSpecified;
            }
            set {
                this.heartrateFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public float speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool speedSpecified {
            get {
                return this.speedFieldSpecified;
            }
            set {
                this.speedFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public short cadence {
            get {
                return this.cadenceField;
            }
            set {
                this.cadenceField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool cadenceSpecified {
            get {
                return this.cadenceFieldSpecified;
            }
            set {
                this.cadenceFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot(Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class limit {
    
        private string typeField;
    
        private float upperField;
    
        private bool upperFieldSpecified;
    
        private float lowerField;
    
        private bool lowerFieldSpecified;
    
        private zone zoneField;
    
        private string indexField;
    
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    
        /// <remarks/>
        public float upper {
            get {
                return this.upperField;
            }
            set {
                this.upperField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool upperSpecified {
            get {
                return this.upperFieldSpecified;
            }
            set {
                this.upperFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public float lower {
            get {
                return this.lowerField;
            }
            set {
                this.lowerField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool lowerSpecified {
            get {
                return this.lowerFieldSpecified;
            }
            set {
                this.lowerFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public zone zone {
            get {
                return this.zoneField;
            }
            set {
                this.zoneField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="nonNegativeInteger")]
        public string index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot(Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class sample {
    
        private sampleType typeField;
    
        private string valuesField;
    
        /// <remarks/>
        public sampleType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    
        /// <remarks/>
        public string values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    public enum sampleType {
    
        /// <remarks/>
        HEARTRATE,
    
        /// <remarks/>
        SPEED,
    
        /// <remarks/>
        CADENCE,
    
        /// <remarks/>
        ALTITUDE,
    
        /// <remarks/>
        POWER,
    
        /// <remarks/>
        POWER_PI,
    
        /// <remarks/>
        POWER_LRB,
    
        /// <remarks/>
        AIR_PRESSURE,
    
        /// <remarks/>
        RUN_CADENCE,
    
        /// <remarks/>
        TEMPERATURE,
    
        /// <remarks/>
        DISTANCE,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="sport-result", Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot("sport-result", Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class sportresult : exercise {
    
        private heartraterange heartrateField;
    
        private sbyte runningindexField;
    
        private bool runningindexFieldSpecified;
    
        private short recordingrateField;
    
        private bool recordingrateFieldSpecified;
    
        private sbyte fatconsumptionField;
    
        private bool fatconsumptionFieldSpecified;
    
        private lap[] lapsField;
    
        private lap[] autolapsField;
    
        private sportspeed sportspeedField;
    
        private floatrange altitudeField;
    
        private limit[] limitsField;
    
        private sample[] samplesField;
    
        /// <remarks/>
        [XmlElement("heart-rate")]
        public heartraterange heartrate {
            get {
                return this.heartrateField;
            }
            set {
                this.heartrateField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("running-index")]
        public sbyte runningindex {
            get {
                return this.runningindexField;
            }
            set {
                this.runningindexField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool runningindexSpecified {
            get {
                return this.runningindexFieldSpecified;
            }
            set {
                this.runningindexFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("recording-rate")]
        public short recordingrate {
            get {
                return this.recordingrateField;
            }
            set {
                this.recordingrateField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool recordingrateSpecified {
            get {
                return this.recordingrateFieldSpecified;
            }
            set {
                this.recordingrateFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("fat-consumption")]
        public sbyte fatconsumption {
            get {
                return this.fatconsumptionField;
            }
            set {
                this.fatconsumptionField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool fatconsumptionSpecified {
            get {
                return this.fatconsumptionFieldSpecified;
            }
            set {
                this.fatconsumptionFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlArrayItem(IsNullable=false)]
        public lap[] laps {
            get {
                return this.lapsField;
            }
            set {
                this.lapsField = value;
            }
        }
    
        /// <remarks/>
        [XmlArrayItem(IsNullable=false)]
        public lap[] autolaps {
            get {
                return this.autolapsField;
            }
            set {
                this.autolapsField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("sport-speed")]
        public sportspeed sportspeed {
            get {
                return this.sportspeedField;
            }
            set {
                this.sportspeedField = value;
            }
        }
    
        /// <remarks/>
        public floatrange altitude {
            get {
                return this.altitudeField;
            }
            set {
                this.altitudeField = value;
            }
        }
    
        /// <remarks/>
        [XmlArrayItem(IsNullable=false)]
        public limit[] limits {
            get {
                return this.limitsField;
            }
            set {
                this.limitsField = value;
            }
        }
    
        /// <remarks/>
        [XmlArrayItem(IsNullable=false)]
        public sample[] samples {
            get {
                return this.samplesField;
            }
            set {
                this.samplesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="sport-speed", Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot("sport-speed", Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class sportspeed {
    
        private float stridelengthavgField;
    
        private bool stridelengthavgFieldSpecified;
    
        private float runningindexField;
    
        private bool runningindexFieldSpecified;
    
        /// <remarks/>
        [XmlElement("stride-length-avg")]
        public float stridelengthavg {
            get {
                return this.stridelengthavgField;
            }
            set {
                this.stridelengthavgField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool stridelengthavgSpecified {
            get {
                return this.stridelengthavgFieldSpecified;
            }
            set {
                this.stridelengthavgFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("running-index")]
        public float runningindex {
            get {
                return this.runningindexField;
            }
            set {
                this.runningindexField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool runningindexSpecified {
            get {
                return this.runningindexFieldSpecified;
            }
            set {
                this.runningindexFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [XmlInclude(typeof(sportresult))]
    [XmlInclude(typeof(result))]
    [XmlInclude(typeof(target))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot(Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class exercise {
    
        private string sportField;
    
        private float distanceField;
    
        private bool distanceFieldSpecified;
    
        private string caloriesField;
    
        private string durationField;
    
        private usersettings usersettingsField;
    
        private move[] movesField;
    
        private zone[] zonesField;
    
        /// <remarks/>
        public string sport {
            get {
                return this.sportField;
            }
            set {
                this.sportField = value;
            }
        }
    
        /// <remarks/>
        public float distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool distanceSpecified {
            get {
                return this.distanceFieldSpecified;
            }
            set {
                this.distanceFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(DataType="nonNegativeInteger")]
        public string calories {
            get {
                return this.caloriesField;
            }
            set {
                this.caloriesField = value;
            }
        }
    
        /// <remarks/>
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("user-settings")]
        public usersettings usersettings {
            get {
                return this.usersettingsField;
            }
            set {
                this.usersettingsField = value;
            }
        }
    
        /// <remarks/>
        [XmlArrayItem(IsNullable=false)]
        public move[] moves {
            get {
                return this.movesField;
            }
            set {
                this.movesField = value;
            }
        }
    
        /// <remarks/>
        [XmlArrayItem(IsNullable=false)]
        public zone[] zones {
            get {
                return this.zonesField;
            }
            set {
                this.zonesField = value;
            }
        }
    }

    /// <remarks/>
    [XmlInclude(typeof(user))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="user-settings", Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot("user-settings", Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class usersettings {
    
        private heartraterange heartrateField;
    
        private sbyte vo2maxField;
    
        private bool vo2maxFieldSpecified;
    
        private float weightField;
    
        private bool weightFieldSpecified;
    
        private float heightField;
    
        private bool heightFieldSpecified;
    
        /// <remarks/>
        [XmlElement("heart-rate")]
        public heartraterange heartrate {
            get {
                return this.heartrateField;
            }
            set {
                this.heartrateField = value;
            }
        }
    
        /// <remarks/>
        public sbyte vo2max {
            get {
                return this.vo2maxField;
            }
            set {
                this.vo2maxField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool vo2maxSpecified {
            get {
                return this.vo2maxFieldSpecified;
            }
            set {
                this.vo2maxFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public float weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool weightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public float height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool heightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="activity-log", Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot("activity-log", Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class activitylog : calendaritem {
    
        private string activetimeField;
    
        private string caloriesField;
    
        /// <remarks/>
        [XmlElement("active-time")]
        public string activetime {
            get {
                return this.activetimeField;
            }
            set {
                this.activetimeField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(DataType="nonNegativeInteger")]
        public string calories {
            get {
                return this.caloriesField;
            }
            set {
                this.caloriesField = value;
            }
        }
    }

    /// <remarks/>
    [XmlInclude(typeof(@event))]
    [XmlInclude(typeof(exercisedata))]
    [XmlInclude(typeof(fitnessdata))]
    [XmlInclude(typeof(note))]
    [XmlInclude(typeof(activitylog))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="calendar-item", Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot("calendar-item", Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class calendaritem {
    
        private string createdField;
    
        private string timeField;
    
        /// <remarks/>
        public string created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
    
        /// <remarks/>
        public string time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="altitude-info", Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot("altitude-info", Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class altitudeinfo {
    
        private floatrange verticalspeedupField;
    
        private floatrange verticalspeeddownField;
    
        private float ascentField;
    
        private bool ascentFieldSpecified;
    
        private float descentField;
    
        private bool descentFieldSpecified;
    
        /// <remarks/>
        [XmlElement("vertical-speed-up")]
        public floatrange verticalspeedup {
            get {
                return this.verticalspeedupField;
            }
            set {
                this.verticalspeedupField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("vertical-speed-down")]
        public floatrange verticalspeeddown {
            get {
                return this.verticalspeeddownField;
            }
            set {
                this.verticalspeeddownField = value;
            }
        }
    
        /// <remarks/>
        public float ascent {
            get {
                return this.ascentField;
            }
            set {
                this.ascentField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool ascentSpecified {
            get {
                return this.ascentFieldSpecified;
            }
            set {
                this.ascentFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public float descent {
            get {
                return this.descentField;
            }
            set {
                this.descentField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool descentSpecified {
            get {
                return this.descentFieldSpecified;
            }
            set {
                this.descentFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="blood-pressure", Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot("blood-pressure", Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class bloodpressure {
    
        private short systolicField;
    
        private bool systolicFieldSpecified;
    
        private short diastolicField;
    
        private bool diastolicFieldSpecified;
    
        /// <remarks/>
        public short systolic {
            get {
                return this.systolicField;
            }
            set {
                this.systolicField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool systolicSpecified {
            get {
                return this.systolicFieldSpecified;
            }
            set {
                this.systolicFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public short diastolic {
            get {
                return this.diastolicField;
            }
            set {
                this.diastolicField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool diastolicSpecified {
            get {
                return this.diastolicFieldSpecified;
            }
            set {
                this.diastolicFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="blood-values", Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot("blood-values", Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class bloodvalues {
    
        private float totalcholesterolField;
    
        private bool totalcholesterolFieldSpecified;
    
        private float ldlcholesterolField;
    
        private bool ldlcholesterolFieldSpecified;
    
        private float hdlcholesterolField;
    
        private bool hdlcholesterolFieldSpecified;
    
        private float triglyseridesField;
    
        private bool triglyseridesFieldSpecified;
    
        private float glucoseField;
    
        private bool glucoseFieldSpecified;
    
        private float insulinField;
    
        private bool insulinFieldSpecified;
    
        /// <remarks/>
        [XmlElement("total-cholesterol")]
        public float totalcholesterol {
            get {
                return this.totalcholesterolField;
            }
            set {
                this.totalcholesterolField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool totalcholesterolSpecified {
            get {
                return this.totalcholesterolFieldSpecified;
            }
            set {
                this.totalcholesterolFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("ldl-cholesterol")]
        public float ldlcholesterol {
            get {
                return this.ldlcholesterolField;
            }
            set {
                this.ldlcholesterolField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool ldlcholesterolSpecified {
            get {
                return this.ldlcholesterolFieldSpecified;
            }
            set {
                this.ldlcholesterolFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("hdl-cholesterol")]
        public float hdlcholesterol {
            get {
                return this.hdlcholesterolField;
            }
            set {
                this.hdlcholesterolField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool hdlcholesterolSpecified {
            get {
                return this.hdlcholesterolFieldSpecified;
            }
            set {
                this.hdlcholesterolFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public float triglyserides {
            get {
                return this.triglyseridesField;
            }
            set {
                this.triglyseridesField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool triglyseridesSpecified {
            get {
                return this.triglyseridesFieldSpecified;
            }
            set {
                this.triglyseridesFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public float glucose {
            get {
                return this.glucoseField;
            }
            set {
                this.glucoseField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool glucoseSpecified {
            get {
                return this.glucoseFieldSpecified;
            }
            set {
                this.glucoseFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public float insulin {
            get {
                return this.insulinField;
            }
            set {
                this.insulinField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool insulinSpecified {
            get {
                return this.insulinFieldSpecified;
            }
            set {
                this.insulinFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="calendar-items", Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot("calendar-items", Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class calendaritems {
    
        private calendaritem[] itemsField;
    
        private string countField;
    
        /// <remarks/>
        [XmlElement("activity-log", typeof(activitylog))]
        [XmlElement("event", typeof(@event))]
        [XmlElement("exercise", typeof(exercisedata))]
        [XmlElement("fitness-data", typeof(fitnessdata))]
        [XmlElement("note", typeof(note))]
        public calendaritem[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="nonNegativeInteger")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot(Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class @event : calendaritem {
    
        private string nameField;
    
        private string noteField;
    
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    
        /// <remarks/>
        public string note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="exercise-data", Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot("exercise-data", Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class exercisedata : calendaritem {
    
        private string sportField;
    
        private string nameField;
    
        private target targetField;
    
        private result resultField;
    
        private sportresult[] sportresultsField;
    
        private string noteField;
    
        /// <remarks/>
        public string sport {
            get {
                return this.sportField;
            }
            set {
                this.sportField = value;
            }
        }
    
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    
        /// <remarks/>
        public target target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
    
        /// <remarks/>
        public result result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    
        /// <remarks/>
        [XmlArray("sport-results")]
        [XmlArrayItem(IsNullable=false)]
        public sportresult[] sportresults {
            get {
                return this.sportresultsField;
            }
            set {
                this.sportresultsField = value;
            }
        }
    
        /// <remarks/>
        public string note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot(Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class target : exercise {
    
        private phase[] phasesField;
    
        /// <remarks/>
        [XmlArrayItem(IsNullable=false)]
        public phase[] phases {
            get {
                return this.phasesField;
            }
            set {
                this.phasesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot(Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class result : exercise {
    
        private heartraterange heartrateField;
    
        private sbyte runningindexField;
    
        private bool runningindexFieldSpecified;
    
        private short recordingrateField;
    
        private bool recordingrateFieldSpecified;
    
        private sbyte fatconsumptionField;
    
        private bool fatconsumptionFieldSpecified;
    
        private lap[] lapsField;
    
        private lap[] autolapsField;
    
        private power powerField;
    
        private speed speedField;
    
        private floatrange altitudeField;
    
        private floatrange temperatureField;
    
        private altitudeinfo altitudeinfoField;
    
        private zone summaryzoneField;
    
        private limit[] limitsField;
    
        private sample[] samplesField;
    
        private activityinfo activityinfoField;
    
        /// <remarks/>
        [XmlElement("heart-rate")]
        public heartraterange heartrate {
            get {
                return this.heartrateField;
            }
            set {
                this.heartrateField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("running-index")]
        public sbyte runningindex {
            get {
                return this.runningindexField;
            }
            set {
                this.runningindexField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool runningindexSpecified {
            get {
                return this.runningindexFieldSpecified;
            }
            set {
                this.runningindexFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("recording-rate")]
        public short recordingrate {
            get {
                return this.recordingrateField;
            }
            set {
                this.recordingrateField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool recordingrateSpecified {
            get {
                return this.recordingrateFieldSpecified;
            }
            set {
                this.recordingrateFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("fat-consumption")]
        public sbyte fatconsumption {
            get {
                return this.fatconsumptionField;
            }
            set {
                this.fatconsumptionField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool fatconsumptionSpecified {
            get {
                return this.fatconsumptionFieldSpecified;
            }
            set {
                this.fatconsumptionFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlArrayItem(IsNullable=false)]
        public lap[] laps {
            get {
                return this.lapsField;
            }
            set {
                this.lapsField = value;
            }
        }
    
        /// <remarks/>
        [XmlArrayItem(IsNullable=false)]
        public lap[] autolaps {
            get {
                return this.autolapsField;
            }
            set {
                this.autolapsField = value;
            }
        }
    
        /// <remarks/>
        public power power {
            get {
                return this.powerField;
            }
            set {
                this.powerField = value;
            }
        }
    
        /// <remarks/>
        public speed speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
            }
        }
    
        /// <remarks/>
        public floatrange altitude {
            get {
                return this.altitudeField;
            }
            set {
                this.altitudeField = value;
            }
        }
    
        /// <remarks/>
        public floatrange temperature {
            get {
                return this.temperatureField;
            }
            set {
                this.temperatureField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("altitude-info")]
        public altitudeinfo altitudeinfo {
            get {
                return this.altitudeinfoField;
            }
            set {
                this.altitudeinfoField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("summary-zone")]
        public zone summaryzone {
            get {
                return this.summaryzoneField;
            }
            set {
                this.summaryzoneField = value;
            }
        }
    
        /// <remarks/>
        [XmlArrayItem(IsNullable=false)]
        public limit[] limits {
            get {
                return this.limitsField;
            }
            set {
                this.limitsField = value;
            }
        }
    
        /// <remarks/>
        [XmlArrayItem(IsNullable=false)]
        public sample[] samples {
            get {
                return this.samplesField;
            }
            set {
                this.samplesField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("activity-info")]
        public activityinfo activityinfo {
            get {
                return this.activityinfoField;
            }
            set {
                this.activityinfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot(Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class speed {
    
        private speedType typeField;
    
        private bool typeFieldSpecified;
    
        private floatrange speed1Field;
    
        private shortrange cadenceField;
    
        /// <remarks/>
        public speedType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("speed")]
        public floatrange speed1 {
            get {
                return this.speed1Field;
            }
            set {
                this.speed1Field = value;
            }
        }
    
        /// <remarks/>
        public shortrange cadence {
            get {
                return this.cadenceField;
            }
            set {
                this.cadenceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    public enum speedType {
    
        /// <remarks/>
        RUNNING,
    
        /// <remarks/>
        CYCLING,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="fitness-data", Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot("fitness-data", Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class fitnessdata : calendaritem {
    
        private heartraterange heartrateField;
    
        private sbyte ownindexField;
    
        private bool ownindexFieldSpecified;
    
        private short ownrelaxField;
    
        private bool ownrelaxFieldSpecified;
    
        private sbyte ownoptimizerField;
    
        private bool ownoptimizerFieldSpecified;
    
        private sbyte walkindexField;
    
        private bool walkindexFieldSpecified;
    
        private short runningindexField;
    
        private bool runningindexFieldSpecified;
    
        private float weightField;
    
        private bool weightFieldSpecified;
    
        private string noteField;
    
        private bool ownindexfromwristunitField;
    
        private bool ownindexfromwristunitFieldSpecified;
    
        private bool ownrelaxfromwristunitField;
    
        private bool ownrelaxfromwristunitFieldSpecified;
    
        private fitnessdetails fitnessdetailsField;
    
        private customvalue[] customvaluesField;
    
        /// <remarks/>
        [XmlElement("heart-rate")]
        public heartraterange heartrate {
            get {
                return this.heartrateField;
            }
            set {
                this.heartrateField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("own-index")]
        public sbyte ownindex {
            get {
                return this.ownindexField;
            }
            set {
                this.ownindexField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool ownindexSpecified {
            get {
                return this.ownindexFieldSpecified;
            }
            set {
                this.ownindexFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("own-relax")]
        public short ownrelax {
            get {
                return this.ownrelaxField;
            }
            set {
                this.ownrelaxField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool ownrelaxSpecified {
            get {
                return this.ownrelaxFieldSpecified;
            }
            set {
                this.ownrelaxFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("own-optimizer")]
        public sbyte ownoptimizer {
            get {
                return this.ownoptimizerField;
            }
            set {
                this.ownoptimizerField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool ownoptimizerSpecified {
            get {
                return this.ownoptimizerFieldSpecified;
            }
            set {
                this.ownoptimizerFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("walk-index")]
        public sbyte walkindex {
            get {
                return this.walkindexField;
            }
            set {
                this.walkindexField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool walkindexSpecified {
            get {
                return this.walkindexFieldSpecified;
            }
            set {
                this.walkindexFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("running-index")]
        public short runningindex {
            get {
                return this.runningindexField;
            }
            set {
                this.runningindexField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool runningindexSpecified {
            get {
                return this.runningindexFieldSpecified;
            }
            set {
                this.runningindexFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public float weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool weightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public string note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("own-index-from-wrist-unit")]
        public bool ownindexfromwristunit {
            get {
                return this.ownindexfromwristunitField;
            }
            set {
                this.ownindexfromwristunitField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool ownindexfromwristunitSpecified {
            get {
                return this.ownindexfromwristunitFieldSpecified;
            }
            set {
                this.ownindexfromwristunitFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("own-relax-from-wrist-unit")]
        public bool ownrelaxfromwristunit {
            get {
                return this.ownrelaxfromwristunitField;
            }
            set {
                this.ownrelaxfromwristunitField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool ownrelaxfromwristunitSpecified {
            get {
                return this.ownrelaxfromwristunitFieldSpecified;
            }
            set {
                this.ownrelaxfromwristunitFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("fitness-details")]
        public fitnessdetails fitnessdetails {
            get {
                return this.fitnessdetailsField;
            }
            set {
                this.fitnessdetailsField = value;
            }
        }
    
        /// <remarks/>
        [XmlArray("custom-values")]
        [XmlArrayItem(IsNullable=false)]
        public customvalue[] customvalues {
            get {
                return this.customvaluesField;
            }
            set {
                this.customvaluesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="fitness-details", Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot("fitness-details", Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class fitnessdetails {
    
        private sbyte bodyageField;
    
        private bool bodyageFieldSpecified;
    
        private sbyte obtainablebodyageField;
    
        private bool obtainablebodyageFieldSpecified;
    
        private float heightField;
    
        private bool heightFieldSpecified;
    
        private float bmiField;
    
        private bool bmiFieldSpecified;
    
        private float waterpercentField;
    
        private bool waterpercentFieldSpecified;
    
        private sbyte fatpercentField;
    
        private bool fatpercentFieldSpecified;
    
        private float bicepsstrengthField;
    
        private bool bicepsstrengthFieldSpecified;
    
        private short crunchesField;
    
        private bool crunchesFieldSpecified;
    
        private short wallsitField;
    
        private bool wallsitFieldSpecified;
    
        private float sitreachField;
    
        private bool sitreachFieldSpecified;
    
        private short situpsField;
    
        private bool situpsFieldSpecified;
    
        private bloodvalues bloodvaluesField;
    
        private bloodpressure bloodpressureField;
    
        private healthriskappraisals healthriskappraisalsField;
    
        /// <remarks/>
        [XmlElement("body-age")]
        public sbyte bodyage {
            get {
                return this.bodyageField;
            }
            set {
                this.bodyageField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool bodyageSpecified {
            get {
                return this.bodyageFieldSpecified;
            }
            set {
                this.bodyageFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("obtainable-body-age")]
        public sbyte obtainablebodyage {
            get {
                return this.obtainablebodyageField;
            }
            set {
                this.obtainablebodyageField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool obtainablebodyageSpecified {
            get {
                return this.obtainablebodyageFieldSpecified;
            }
            set {
                this.obtainablebodyageFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public float height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool heightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public float bmi {
            get {
                return this.bmiField;
            }
            set {
                this.bmiField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool bmiSpecified {
            get {
                return this.bmiFieldSpecified;
            }
            set {
                this.bmiFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("water-percent")]
        public float waterpercent {
            get {
                return this.waterpercentField;
            }
            set {
                this.waterpercentField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool waterpercentSpecified {
            get {
                return this.waterpercentFieldSpecified;
            }
            set {
                this.waterpercentFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("fat-percent")]
        public sbyte fatpercent {
            get {
                return this.fatpercentField;
            }
            set {
                this.fatpercentField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool fatpercentSpecified {
            get {
                return this.fatpercentFieldSpecified;
            }
            set {
                this.fatpercentFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("biceps-strength")]
        public float bicepsstrength {
            get {
                return this.bicepsstrengthField;
            }
            set {
                this.bicepsstrengthField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool bicepsstrengthSpecified {
            get {
                return this.bicepsstrengthFieldSpecified;
            }
            set {
                this.bicepsstrengthFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public short crunches {
            get {
                return this.crunchesField;
            }
            set {
                this.crunchesField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool crunchesSpecified {
            get {
                return this.crunchesFieldSpecified;
            }
            set {
                this.crunchesFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("wall-sit")]
        public short wallsit {
            get {
                return this.wallsitField;
            }
            set {
                this.wallsitField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool wallsitSpecified {
            get {
                return this.wallsitFieldSpecified;
            }
            set {
                this.wallsitFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("sit-reach")]
        public float sitreach {
            get {
                return this.sitreachField;
            }
            set {
                this.sitreachField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool sitreachSpecified {
            get {
                return this.sitreachFieldSpecified;
            }
            set {
                this.sitreachFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("sit-ups")]
        public short situps {
            get {
                return this.situpsField;
            }
            set {
                this.situpsField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool situpsSpecified {
            get {
                return this.situpsFieldSpecified;
            }
            set {
                this.situpsFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("blood-values")]
        public bloodvalues bloodvalues {
            get {
                return this.bloodvaluesField;
            }
            set {
                this.bloodvaluesField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("blood-pressure")]
        public bloodpressure bloodpressure {
            get {
                return this.bloodpressureField;
            }
            set {
                this.bloodpressureField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("health-risk-appraisals")]
        public healthriskappraisals healthriskappraisals {
            get {
                return this.healthriskappraisalsField;
            }
            set {
                this.healthriskappraisalsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="health-risk-appraisals", Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot("health-risk-appraisals", Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class healthriskappraisals {
    
        private hraqDepression depressionField;
    
        private bool depressionFieldSpecified;
    
        private hraqHeartDisease heartdiseaseField;
    
        private bool heartdiseaseFieldSpecified;
    
        private hraqNutrition nutritionField;
    
        private bool nutritionFieldSpecified;
    
        private hraqStress stressField;
    
        private bool stressFieldSpecified;
    
        /// <remarks/>
        public hraqDepression depression {
            get {
                return this.depressionField;
            }
            set {
                this.depressionField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool depressionSpecified {
            get {
                return this.depressionFieldSpecified;
            }
            set {
                this.depressionFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("heart-disease")]
        public hraqHeartDisease heartdisease {
            get {
                return this.heartdiseaseField;
            }
            set {
                this.heartdiseaseField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool heartdiseaseSpecified {
            get {
                return this.heartdiseaseFieldSpecified;
            }
            set {
                this.heartdiseaseFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public hraqNutrition nutrition {
            get {
                return this.nutritionField;
            }
            set {
                this.nutritionField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool nutritionSpecified {
            get {
                return this.nutritionFieldSpecified;
            }
            set {
                this.nutritionFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        public hraqStress stress {
            get {
                return this.stressField;
            }
            set {
                this.stressField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool stressSpecified {
            get {
                return this.stressFieldSpecified;
            }
            set {
                this.stressFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    public enum hraqDepression {
    
        /// <remarks/>
        LOW,
    
        /// <remarks/>
        MILD,
    
        /// <remarks/>
        MODERATE,
    
        /// <remarks/>
        SEVERE,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    public enum hraqHeartDisease {
    
        /// <remarks/>
        LOW,
    
        /// <remarks/>
        LOW_TO_MODERATE,
    
        /// <remarks/>
        MODERATE_TO_HIGH,
    
        /// <remarks/>
        HIGH,
    
        /// <remarks/>
        VERY_HIGH,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    public enum hraqNutrition {
    
        /// <remarks/>
        POOR,
    
        /// <remarks/>
        FAIR,
    
        /// <remarks/>
        AVERAGE,
    
        /// <remarks/>
        GOOD,
    
        /// <remarks/>
        EXCELLENT,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    public enum hraqStress {
    
        /// <remarks/>
        LOW,
    
        /// <remarks/>
        MILD,
    
        /// <remarks/>
        MODERATE,
    
        /// <remarks/>
        SEVERE,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="custom-value", Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot("custom-value", Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class customvalue {
    
        private string nameField;
    
        private string valueField;
    
        private string unitField;
    
        private string descriptionField;
    
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    
        /// <remarks/>
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot(Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class note : calendaritem {
    
        private string textField;
    
        /// <remarks/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="custom-values", Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot("custom-values", Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class customvalues {
    
        private customvalue[] customvalueField;
    
        /// <remarks/>
        [XmlElement("custom-value")]
        public customvalue[] customvalue {
            get {
                return this.customvalueField;
            }
            set {
                this.customvalueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="polar-exercise-data", Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot("polar-exercise-data", Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class polarexercisedata {
    
        private user userField;
    
        private calendaritems calendaritemsField;
    
        private double versionField;
    
        /// <remarks/>
        public user user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("calendar-items")]
        public calendaritems calendaritems {
            get {
                return this.calendaritemsField;
            }
            set {
                this.calendaritemsField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public double version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.polarpersonaltrainer.com")]
    [XmlRoot(Namespace="http://www.polarpersonaltrainer.com", IsNullable=false)]
    public partial class user : usersettings {
    
        private string emailField;
    
        private string nicknameField;
    
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    
        /// <remarks/>
        public string nickname {
            get {
                return this.nicknameField;
            }
            set {
                this.nicknameField = value;
            }
        }
    }
}